---
# tasks file for apacherole
- name: Install required dependencies
  apt:
    name: openjdk-11-jdk
    state: present
  become: yes

- name: Create Tomcat group
  group:
    name: "{{ tomcat_group }}"
    state: present

- name: Create Tomcat user
  user:
    name: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    shell: /bin/false
    system: yes

- name: Ensure Tomcat installation directory exists  # 🔹 Add this task
  file:
    path: "{{ tomcat_install_dir }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: '0755'
  become: yes
- name: Download Tomcat
  get_url:
    url: "{{ tomcat_download_url }}"
    dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
  register: download_tomcat

- name: Extract Tomcat
  unarchive:
    src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_install_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
  become: yes

- name: Set permissions for Tomcat
  file:
    path: "{{ tomcat_install_dir }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: '0755'
    recurse: yes

- name: Create Tomcat service file
  template:
    src: tomservice.j2
    dest: /etc/systemd/system/tomcat.service
  notify: restart tomcat
- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start and enable Tomcat service
  systemd:
    name: tomcat
    state: started
    enabled: yes

- name: Open firewall for apache on Ubuntu
  ufw:
    rule: allow
    port: "8084"
    proto: tcp
